# Generated by Django 2.1.2 on 2018-11-26 04:53

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_title', models.CharField(max_length=10)),
                ('goods_pic', models.ImageField(upload_to='df_goods')),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('goods_price_unit', models.CharField(default='500g', max_length=10)),
                ('isDelete', models.BooleanField(default=False)),
                ('goods_click', models.IntegerField(default=0)),
                ('goods_describe', models.CharField(max_length=100)),
                ('goods_left', models.IntegerField(default=0)),
                ('goods_detail', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_title', models.CharField(max_length=10)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='goods_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='df_goods.TypeInfo'),
        ),
    ]
