# Generated by Django 2.1.2 on 2018-11-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinfo',
            name='goods_detail_pic',
            field=models.ImageField(null=True, upload_to='df_goods'),
        ),
    ]
