# Generated by Django 2.1.2 on 2018-11-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_pwd', models.CharField(max_length=40)),
                ('user_email', models.CharField(max_length=30)),
                ('accepter_name', models.CharField(default='', max_length=10)),
                ('accepter_address', models.CharField(default='', max_length=100)),
                ('accepter_postcode', models.CharField(default='', max_length=6)),
                ('accepter_phone_number', models.CharField(default='', max_length=11)),
            ],
        ),
        migrations.DeleteModel(
            name='uer_info',
        ),
    ]
